name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          export LC_CTYPE=C
          export LANG=C
          tr -dc "[:graph:]" < /dev/urandom | head -c 4
