name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          brew install --cask keepassxc
          keepassxc-cli db-create --quiet --set-password ~/test.kdbx << EOF
          test
          test
          EOF
          
      - run: open -a "KeePassXC" ~/test.kdbx
