name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          LC_CTYPE=C tr -dc '[:graph:]' < /dev/urandom | iconv -c -f UTF-8 -t UTF-8 | head -c 4

