name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          timeout 1s LC_CTYPE="C" LC_ALL="C" tr -dc '[:graph:]' < /dev/urandom | head -c 4

