name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          # head -c 10 /dev/urandom | LC_CTYPE="C" LC_ALL="C" tr -dc '[:graph:]'
          password="$(LC_CTYPE=C tr -dc '[:graph:]' < /dev/urandom | head -c 4 || true)"
          echo "${password}"
